Repository FRONTENDSCHOOL7/final-18-moamoa, pull requests merged in 2023-11, with the labels that each got.

#137 [🌈Style] 채팅방 , 채팅목록 마크업 구현 완료했습니다.
  moamoa/src/Assets/icons/icon-img-button.svg
  moamoa/src/Components/Common/ChatPhoto.jsx
  moamoa/src/Components/Common/HeaderChat.jsx
  moamoa/src/Components/Common/ProductImgBox.jsx
  moamoa/src/Pages/Chat/ChatList.jsx
  moamoa/src/Pages/Chat/ChatRoom.jsx
  moamoa/src/Pages/Chat/ChatRoomDarkHorse.jsx
  moamoa/src/Pages/Chat/ChatRoomKim.jsx
  moamoa/src/Pages/Chat/ChatRoomSumiDad.jsx
  moamoa/src/Router/AppRoutes.js
Labels: ✅ 완료, 🌈 스타일

#140 [🌈 Style] 회원가입 및 로그인 페이지 스타일 적용
  moamoa/src/Assets/icons/icon-email.svg
  moamoa/src/Assets/icons/icon-lock.svg
  moamoa/src/Components/Common/FormLoginAndJoin.jsx
  moamoa/src/Hooks/Sign/useJoin.jsx
  moamoa/src/Hooks/Sign/useLogin.jsx
  moamoa/src/Pages/Join/Join.jsx
  moamoa/src/Pages/Login/Login.jsx
Labels: ✅ 완료, 🌈 스타일

#141 [✨ Feature] 상품 삭제 기능 구현
  moamoa/src/API/Product/ProductDeleteAPI.jsx
  moamoa/src/Pages/Product/AskBtn.jsx
Labels: ✨ 기능추가, ✅ 완료

#146 [🔧 Fix] 상세페이지 오류 해결
  moamoa/src/Components/Comment/AddCommentBtn.jsx
  moamoa/src/Components/Comment/Comment.jsx
  moamoa/src/Components/Comment/CommentItem.jsx
  moamoa/src/Components/Common/CommentMoreBtn.jsx
  moamoa/src/Components/Modal/DeleteModal.jsx
  moamoa/src/Components/Post/PostCardItem.jsx
  moamoa/src/Components/Post/PostCardList.jsx
  moamoa/src/Pages/Home/Home.jsx
  moamoa/src/Pages/Post/PostDetail.jsx
Labels: ✅ 완료, 🔧 수정완료

#148 [🌈 Style] 프로필 설정 페이지 스타일 적용
  moamoa/src/Assets/images/profile-img.svg
  moamoa/src/Components/Common/FormLoginAndJoin.jsx
  moamoa/src/GlobalStyle.jsx
  moamoa/src/Hooks/Sign/useJoin.jsx
  moamoa/src/Pages/Join/Join.jsx
  moamoa/src/Pages/Login/Login.jsx
Labels: ✅ 완료, 🌈 스타일

#150 [🔧 Fix] 상품 상세페이지 출력 오류 해결 및 삭제 모달 추가
  moamoa/src/Components/Modal/DeleteModal.jsx
  moamoa/src/Components/Post/PostCardItem.jsx
  moamoa/src/Components/Post/PostCardList.jsx
  moamoa/src/Pages/Product/AskBtn.jsx
  moamoa/src/Pages/Product/ProductDetail.jsx
Labels: 🔧 수정완료

#151 [🔧fix] 버튼 컴포넌트 콘솔 오류와 푸터 콘솔 오류 해결했습니다.
  moamoa/src/Components/Common/Button.jsx
  moamoa/src/Components/Common/FollowUser.jsx
  moamoa/src/Components/Common/FollowingUser.jsx
  moamoa/src/Components/Common/Footer.jsx
  moamoa/src/Pages/Product/ProductList.jsx
Labels: ✅ 완료, 🔧 수정완료

#155 [🔧 Fix] Home 오류 발생 초기화 진행
  moamoa/src/API/Comment/CommnetDeleteAPI.jsx
  moamoa/src/API/Post/PostDeleteAPI.jsx
  moamoa/src/Components/Comment/CommentItem.jsx
  moamoa/src/Components/Comment/CommentMoreBtn.jsx
  moamoa/src/Components/Common/CommentMoreBtn.jsx
  moamoa/src/Components/Modal/DeleteModal.jsx
Labels: 🔧 수정완료

#156 [🌈 Style] 상품 등록 및 상품 수정 페이지 스타일 적용
  moamoa/src/Assets/icons/icon-calendar.png
  moamoa/src/Assets/images/img-product-default.png
  moamoa/src/Components/Common/ProductSharedStyle.jsx
  moamoa/src/Pages/Product/AddProduct.jsx
  moamoa/src/Pages/Product/EditProduct.jsx
Labels: ✅ 완료, 🌈 스타일

#159 [✨Feature] 검색 기능 구현
  moamoa/src/API/Product/ProductListAPI.jsx
  moamoa/src/API/Search/SearchAPI.jsx
  moamoa/src/Assets/icons/icon-message-fill.svg
  moamoa/src/Components/Common/HeaderSearch.jsx
  moamoa/src/Components/Post/PostCardItem.jsx
  moamoa/src/Components/Post/PostCardList.jsx
  moamoa/src/Hooks/Search/useDebounce.jsx
  moamoa/src/Pages/Search/Search.jsx
Labels: ✨ 기능추가, 🚀 진행중

#160 [🌈 Style] 프로필 수정 페이지 스타일 작업
  moamoa/src/Assets/icons/icon-usertype-check.svg
  moamoa/src/Components/Common/ProfileDetail.jsx
  moamoa/src/Components/Common/ProfileDetailPost.jsx
  moamoa/src/Components/Common/ProfileDetailProduct.jsx
  moamoa/src/Components/Post/PostCardList.jsx
  moamoa/src/Pages/Home/Home.jsx
  moamoa/src/Pages/Post/UloadEditPostStyle.jsx
  moamoa/src/Pages/Profile/EditProfile.jsx
Labels: ✅ 완료, 🌈 스타일

#164 [✨Feature/🔧 Fix] 팔로잉, 팔로우, 검색에서 프로필로 이동 추가, 팔로잉 팔로우 오류 수정
  moamoa/src/API/Product/ProductListAPI.jsx
  moamoa/src/Components/Common/FollowUser.jsx
  moamoa/src/Components/Common/FollowingUser.jsx
  moamoa/src/Components/Common/FormLoginAndJoin.jsx
  moamoa/src/Components/Common/HeaderProductList.jsx
  moamoa/src/Components/Post/PostCardItem.jsx
  moamoa/src/Pages/Follow/FollowerList.jsx
  moamoa/src/Pages/Follow/FollowingList.jsx
  moamoa/src/Pages/Search/Search.jsx
Labels: ✨ 기능추가, ✅ 완료

#170 [✨ Feature] 좋아요 기능 추가
  moamoa/src/API/Post/HeartCountDownAPI.jsx
  moamoa/src/API/Post/HeartCountUpAPI.jsx
  moamoa/src/Components/Home/HomePostCardList.jsx
  moamoa/src/Components/Post/PostCardItem.jsx
  moamoa/src/Components/Post/PostCardList.jsx
  moamoa/src/Pages/Post/PostDetail.jsx
Labels: ✨ 기능추가, ✅ 완료

#171 [✨ Feature]: 대화방 전송 버튼 활성화, 이미지 삭제 버튼 , 채팅방 나가기 기능 추가
  moamoa/src/Components/Common/ChatMoreBtn.jsx
  moamoa/src/Components/Common/Container.jsx
  moamoa/src/Components/Common/HeaderChat.jsx
  moamoa/src/Pages/Chat/ChatList.jsx
  moamoa/src/Pages/Chat/ChatRoomDarkHorse.jsx
  moamoa/src/Pages/Chat/ChatRoomKim.jsx
  moamoa/src/Pages/Chat/ChatRoomSumiDad.jsx
  moamoa/src/Pages/Product/ProductList.jsx
Labels: ✨ 기능추가, ✅ 완료, 🌈 스타일

#174 [ 🌈 Style ] 홈 화면 및 게시글 상세 스타일 수정
  moamoa/src/Components/Comment/Comment.jsx
  moamoa/src/Components/Comment/CommentDelModal.jsx
  moamoa/src/Components/Home/HomePostCardList.jsx
  moamoa/src/Components/Post/PostCardItem.jsx
  moamoa/src/Components/Post/PostCardList.jsx
  moamoa/src/GlobalStyle.jsx
  moamoa/src/Pages/Home/Home.jsx
  moamoa/src/Pages/Post/PostDetail.jsx
Labels: 🔧 수정완료, 🌈 스타일

#173 [✨ Feature/🌈 Style] 프로필 상세 페이지 모달작업 및 로그아웃 기능 추가
  moamoa/src/Components/Common/HeaderKebab.jsx
  moamoa/src/Components/Common/HeaderProductList.jsx
  moamoa/src/Components/Common/HeaderSearch.jsx
  moamoa/src/Components/Common/ProfileDetailPost.jsx
  moamoa/src/Components/Modal/ConfirmLogoutModal.jsx
  moamoa/src/Components/Modal/FooterModal.jsx
  moamoa/src/Components/Modal/LogoutModal.jsx
  moamoa/src/Pages/Chat/ChatList.jsx
  moamoa/src/Pages/Post/EditPost.jsx
  moamoa/src/Pages/Post/PostDetail.jsx
  moamoa/src/Pages/Profile/MyProfile.jsx
  moamoa/src/Pages/Profile/YourProfile.jsx
Labels: ✨ 기능추가, ✅ 완료, 🌈 스타일

#176 [🔧 Fix] 게시글 상세페이지 오류 수정
  moamoa/src/Components/Post/PostCardList.jsx
  moamoa/src/Pages/Post/PostDetail.jsx
Labels: 🔧 수정완료

#177 [🔧 Fix] 기본 프로필 이미지로 회원가입 시 프로필 이미지가 뜨지 않는 문제 수정
  moamoa/src/API/Img/UploadImageAPI.jsx
  moamoa/src/Hooks/Sign/useJoin.jsx
  moamoa/src/Pages/Join/Join.jsx
Labels: ✅ 완료

#183 [🌈style:] 검색 결과가 없을 때 스타일, 기업과 일반 회원 구분 텍스트 필터링
  moamoa/src/Assets/icons/icon-searchNotFound.svg
  moamoa/src/Components/Common/Footer.jsx
  moamoa/src/Hooks/Search/useDebounce.jsx
  moamoa/src/Pages/Search/Search.jsx
  moamoa/src/Pages/Splash/Landing.jsx
Labels: ✅ 완료, 🌈 스타일

#184 [✨ Feature] 회원가입(프로필 설정) 글자 수 입력 조건 설정
  moamoa/src/Hooks/Sign/useJoin.jsx
  moamoa/src/Pages/Join/Join.jsx
Labels: ✨ 기능추가, ✅ 완료

#185 [🌈 Style] 404 페이지 스타일 작업
  moamoa/src/Assets/icons/404.svg
  moamoa/src/Pages/Error.jsx
  moamoa/src/Pages/NotFound.jsx
  moamoa/src/Router/AppRoutes.js
Labels: ✅ 완료, 🌈 스타일

#188 [🔧 Fix] 상품 추가 페이지에서 이미지가 뜨지 않는 오류
  moamoa/src/Pages/Product/AddProduct.jsx
  moamoa/src/Pages/Product/EditProduct.jsx
Labels: ✅ 완료

#189 [ 🔧 Fix ] 새로고침 문제 해결 및 스타일 수정
  moamoa/src/Components/Comment/Comment.jsx
  moamoa/src/Components/Common/ProfileDetailPost.jsx
  moamoa/src/Components/Common/ProfileDetailProduct.jsx
  moamoa/src/Components/Home/HomePostCardList.jsx
  moamoa/src/Components/Modal/DeleteModal.jsx
  moamoa/src/Components/Modal/ReportModal copy.jsx
  moamoa/src/Components/Modal/ReportModal.jsx
  moamoa/src/Components/Post/PostCardList.jsx
  moamoa/src/Pages/Home/Home.jsx
  moamoa/src/Pages/Post/PostDetail.jsx
  moamoa/src/Pages/Product/AskBtn.jsx
Labels: ✅ 완료, 🔧 수정완료

#192 [🔧 Fix] Home 화면 스타일 수정
  moamoa/src/Pages/Home/Home.jsx
  moamoa/src/Pages/Home/HomeFeed.jsx
Labels: 🔧 수정완료

#193 [🌈 Style] 페이지 상단에 헤더 위치 고정
  moamoa/src/Assets/icons/icon- more-vertical.svg
  moamoa/src/Components/Common/ChatMoreBtn.jsx
  moamoa/src/Components/Common/HeaderAddProduct.jsx
  moamoa/src/Components/Common/HeaderBasic.jsx
  moamoa/src/Components/Common/HeaderChat.jsx
  moamoa/src/Components/Common/HeaderFollowingList.jsx
  moamoa/src/Components/Common/HeaderFollwerList.jsx
  moamoa/src/Components/Common/HeaderHome.jsx
  moamoa/src/Components/Common/HeaderKebab.jsx
  moamoa/src/Components/Common/HeaderProductList.jsx
  moamoa/src/Components/Common/HeaderSearch.jsx
  moamoa/src/Components/Common/ProductSharedStyle.jsx
  moamoa/src/Components/Post/PostCardList.jsx
  moamoa/src/Pages/Chat/ChatList.jsx
  moamoa/src/Pages/Chat/ChatRoomDarkHorse.jsx
  moamoa/src/Pages/Chat/ChatRoomKim.jsx
  moamoa/src/Pages/Chat/ChatRoomSumiDad.jsx
  moamoa/src/Pages/Home/Home.jsx
  moamoa/src/Pages/Home/HomeFeed.jsx
  moamoa/src/Pages/Post/EditPost.jsx
  moamoa/src/Pages/Post/PostDetail.jsx
  moamoa/src/Pages/Post/UploadEditPostStyle.jsx
  moamoa/src/Pages/Post/UploadPost.jsx
  moamoa/src/Pages/Product/ProductDetail.jsx
  moamoa/src/Pages/Profile/EditProfile.jsx
  moamoa/src/Pages/Profile/MyProfile.jsx
  moamoa/src/Pages/Profile/YourProfile.jsx
  moamoa/src/Pages/Search/Search.jsx
Labels: ✅ 완료, 🌈 스타일

#196 [🔧 Fix] 상품 등록과 상품 수정 페이지 스타일 수정 및 상품 명 글자 수 제한 설정
  moamoa/src/Components/Common/ProductSharedStyle.jsx
  moamoa/src/Pages/Product/AddProduct.jsx
  moamoa/src/Pages/Product/EditProduct.jsx
Labels: 🔧 수정완료

#198 [✨ Feature] 사용자의 로그인 상태에 따른 경로 접근 제한
  moamoa/src/Components/Common/HeaderKebab.jsx
  moamoa/src/Router/AppRoutes.js
  moamoa/src/Router/PrivateRoute.js
Labels: ✨ 기능추가, ✅ 완료

#200 [🔧 Fix] 프로필 설정 시 사용자명 글자 수 입력조건 미충족임에도 버튼 활성화되는 문제 및 스타일 수정
  moamoa/src/Components/Common/FormLoginAndJoin.jsx
  moamoa/src/Pages/Join/Join.jsx
  moamoa/src/Pages/Login/Login.jsx
Labels: 🔧 수정완료

#201 [♻️ Refactor] PostDelete API 분리 및 DeleteModal 코드 수정
  moamoa/src/API/Post/PostDeleteAPI.jsx
  moamoa/src/API/Post/PostDetailAPI.jsx
  moamoa/src/API/Product/ProductDeleteAPI.jsx
  moamoa/src/Components/Modal/DeleteModal.jsx
  moamoa/src/Components/Post/PostCardItem.jsx
  moamoa/src/Pages/Post/PostDetail.jsx
Labels: ♻️ 리팩토링

#203 [✨ Feature / 🌈 Style / 🔧 Fix] 프로필 수정 페이지 닉네님 작성 오류 수정 및 글자수 제한 기능 추가 및 프로필 상세페이지 디자인 수정
  moamoa/src/Components/Common/ProfileDetailPost.jsx
  moamoa/src/Components/Common/ProfileDetailProduct.jsx
  moamoa/src/Pages/Follow/FollowerList.jsx
  moamoa/src/Pages/Follow/FollowingList.jsx
  moamoa/src/Pages/Home/HomeFeed.jsx
  moamoa/src/Pages/Product/ProductList.jsx
  moamoa/src/Pages/Profile/EditProfile.jsx
  moamoa/src/Pages/Profile/MyProfile.jsx
  moamoa/src/Pages/Profile/YourProfile.jsx
Labels: ✨ 기능추가, ✅ 완료, 🔧 수정완료, 🌈 스타일

#205 [♻️ Refactor] 로그인과 회원가입 공통 CSS 정리 및 API 응답 에러 코드 수정
  moamoa/src/API/Auth/JoinAPI.jsx
  moamoa/src/API/Auth/LoginAPI.jsx
  moamoa/src/API/Img/UploadImageAPI.jsx
  moamoa/src/API/Product/ProductDeleteAPI.jsx
  moamoa/src/API/Product/ProductDetailAPI.jsx
  moamoa/src/API/Product/ProductEditAPI.jsx
  moamoa/src/API/Product/ProductUploadAPI.jsx
  moamoa/src/API/Valid/AccountValidAPI.jsx
  moamoa/src/API/Valid/EmailValidAPI.jsx
  moamoa/src/Components/Common/FormLoginAndJoin.jsx
  moamoa/src/Hooks/Sign/useJoin.jsx
  moamoa/src/Hooks/Sign/useLogin.jsx
  moamoa/src/Pages/Product/AddProduct.jsx
  moamoa/src/Pages/Product/EditProduct.jsx
  moamoa/src/Pages/Sign/Join.jsx
  moamoa/src/Pages/Sign/Login.jsx
  moamoa/src/Router/AppRoutes.js
Labels: ✅ 완료, ♻️ 리팩토링

#206 [♻️ Refactor] 게시글 상세 API 분리
  moamoa/src/API/Post/HeartCountDownAPI.jsx
  moamoa/src/API/Post/HeartCountUpAPI.jsx
  moamoa/src/API/Post/PostDetailAPI.jsx
  moamoa/src/Components/Comment/CommentDelModal.jsx
  moamoa/src/Components/Comment/CommentReportModal.jsx
  moamoa/src/Components/Modal/DeleteModal.jsx
  moamoa/src/Components/Modal/FooterModal.jsx
  moamoa/src/Components/Modal/ReportModal.jsx
  moamoa/src/Components/Post/PostCardItem.jsx
  moamoa/src/Pages/Post/PostDetail.jsx
Labels: ✅ 완료, ♻️ 리팩토링

#208 [🔧 Fix] 다른 화면에서 로그인 화면으로 이동 시 local storage에 값이 남아있는 문제
  moamoa/src/API/Post/PostDetailAPI.jsx
  moamoa/src/Hooks/Sign/useLogin.jsx
Labels: ✅ 완료

#211 [ 🔧Fix ] 게시글 상단 유저 프로필 이동 경로 수정
  moamoa/src/Components/Comment/AddCommentBtn.jsx
  moamoa/src/Components/Home/HomePostCardList.jsx
  moamoa/src/Components/Modal/ReportModal.jsx
  moamoa/src/Components/Post/PostCardItem.jsx
  moamoa/src/Components/Post/PostCardList.jsx
  moamoa/src/Components/Post/PostCardUser.jsx
  moamoa/src/Pages/Product/AskBtn.jsx
  moamoa/src/Pages/Product/ProductDetail.jsx
Labels: 🔧 수정완료

#213 ]🔧fix] 검색페이지 이미지 위로 쏠림 수정 , 스플래시 화면 festival 폰트 수정 , 로그인 유저 스플래시 화면 보여주고 홈 화면 이동, 채팅방 더보기 모달 dim처리 수정
  moamoa/src/Assets/images/Festival.svg
  moamoa/src/Components/Common/HeaderChat.jsx
  moamoa/src/Pages/Chat/ChatRoomDarkHorse.jsx
  moamoa/src/Pages/Chat/ChatRoomKim.jsx
  moamoa/src/Pages/Chat/ChatRoomSumiDad.jsx
  moamoa/src/Pages/Search/Search.jsx
  moamoa/src/Pages/Splash/Landing.jsx
Labels: ✅ 완료, 🌈 스타일

#215 [🔧 Fix] 팔로우/언팔로우 버튼 기능 이슈 해결
  moamoa/src/API/Profile/FollowAPI.jsx
  moamoa/src/API/Profile/GetYourinfoAPI.jsx
  moamoa/src/API/Profile/UnFollowAPI.jsx
  moamoa/src/Components/Common/FollowButton.jsx
  moamoa/src/Components/Common/ProfileDetail.jsx
  moamoa/src/Pages/Profile/MyProfile.jsx
  moamoa/src/Pages/Profile/YourProfile.jsx
Labels: ✅ 완료, 🔧 수정완료

#218 [🔧fix]검색 페이지 검색 내용을 지우면 안내문구, 로딩 이미지 추가
  moamoa/src/Components/Common/HeaderChat.jsx
  moamoa/src/Pages/Search/Loader.jsx
  moamoa/src/Pages/Search/Search.jsx
Labels: ✨ 기능추가, ✅ 완료, 🌈 스타일

#220 [🔧 Fix] 삭제 오류 해결
  moamoa/src/API/Post/PostDeleteAPI.jsx
  moamoa/src/API/Post/PostDetailAPI.jsx
  moamoa/src/API/Product/ProductDeleteAPI.jsx
  moamoa/src/Assets/icons/character-blue.png
  moamoa/src/Components/Modal/DeleteModal.jsx
  moamoa/src/Components/Modal/FooterModal.jsx
  moamoa/src/Components/Modal/NoticeModal.jsx
  moamoa/src/Components/Post/MyPostMoreBtn.jsx
  moamoa/src/Components/Post/PostCardItem.jsx
  moamoa/src/Pages/Post/PostDetail.jsx
Labels: ✅ 완료, 🔧 수정완료

#221 상대 프로필에서 메시지 버튼을 chatList 경로에서 상대 userName으로 연결된 채팅방으로 바꾸었습니다.
  moamoa/src/Pages/Profile/YourProfile.jsx
Labels: ✨ 기능추가, ✅ 완료

#223 [🔧 Fix] 행사 삭제 오류 해결
  moamoa/src/API/Product/ProductDeleteAPI.jsx
  moamoa/src/Pages/Product/AskBtn.jsx
Labels: ✅ 완료, 🔧 수정완료

#226 [🔧 Fix] 콘솔 에러 해결
  moamoa/src/Pages/Post/EditPost.jsx
  moamoa/src/Pages/Post/UploadPost.jsx
Labels: ✅ 완료, 🔧 수정완료

#228 [🔧 Fix] 등록이 오래된 상품 상세 페이지 불러오기
  moamoa/src/Pages/Product/ProductDetail.jsx
Labels: ✅ 완료

#230 [🔧fix] 프로필 페이지와 홈 화면의 콘솔 오류를 수정하였습니다.
  moamoa/src/Components/Common/ProfileDetailPost.jsx
  moamoa/src/Components/Home/HomePostCardList.jsx
  moamoa/src/Components/Post/PostCardItem.jsx
  moamoa/src/Components/Post/PostCardList.jsx
Labels: ✅ 완료, 🔧 수정완료

#232 [ 🔧 Fix ] 게시글 및 검색화면 공식 마크 출력
  moamoa/src/Components/Home/HomePostCardList.jsx
  moamoa/src/Components/Post/PostCardItem.jsx
  moamoa/src/Components/Post/PostCardList.jsx
  moamoa/src/Components/Post/PostCardUser.jsx
  moamoa/src/Pages/Search/Search.jsx
Labels: ✅ 완료, 🔧 수정완료

#234 [🔧 Fix] 불필요한 코드 제거 및 신고 알림 모달 추가
  moamoa/src/Components/Comment/CommentDelModal.jsx
  moamoa/src/Components/Comment/CommentItem.jsx
  moamoa/src/Components/Comment/CommentMoreBtn.jsx
  moamoa/src/Components/Comment/CommentReportModal.jsx
  moamoa/src/Components/Modal/NoticeReportModal.jsx
  moamoa/src/Components/Modal/ReportModal.jsx
  moamoa/src/Components/Post/PostCardItem.jsx
Labels: 🔧 수정완료

#235 [✨ Feature] 배포 시 테스트 계정 설정
  moamoa/src/Hooks/Sign/useLogin.jsx
Labels: ✅ 완료

#239 [ 🔧 Fix/ 🌈 Style] 로그아웃 모달 스타일 수정 및 YourProfile.jsx userName 변경
  moamoa/src/Assets/images/MOAMOA.png
  moamoa/src/Components/Modal/ConfirmLogoutModal.jsx
  moamoa/src/Components/Modal/LogoutModal.jsx
  moamoa/src/Pages/Chat/ChatRoomAccount.jsx
  moamoa/src/Pages/Profile/YourProfile.jsx
Labels: 🔧 수정완료

#237 [🌈 Style] 축제리스트 로딩시간에 이미지 추가
  moamoa/src/Components/Comment/CommentDelModal.jsx
  moamoa/src/Components/Post/PostCardItem.jsx
  moamoa/src/Pages/Product/LoaderProductList.jsx
  moamoa/src/Pages/Product/ProductList.jsx
  moamoa/src/Pages/Profile/YourProfile.jsx
Labels: ✅ 완료, 🌈 스타일

#244 [🌈 Style] 웹 페이지 제목 및 파비콘 설정
  moamoa/public/favicon.ico
  moamoa/public/index.html
Labels: ✅ 완료

#246 [🔧 Fix] 프로필 수정 페이지 행사 삭제 후 업데이트 이슈 해결
  moamoa/src/Components/Common/ProfileDetailProduct.jsx
Labels: ✅ 완료, 🔧 수정완료

#248 [Delete] 더미 파일 삭제
  .DS_Store
Labels: 🗑️ 삭제

#251 Fix: 상품 수정페이지 경로 수정
  moamoa/README.md
  moamoa/src/Pages/Product/AskBtn.jsx
  moamoa/src/Pages/Product/EditProduct.jsx
  moamoa/src/Router/AppRoutes.js
Labels: ✅ 완료, 🔧 수정

#252 [♻️ Refactor] 상품 상세페이지 API 분리 및 함수명, 변수명 수정
  moamoa/src/API/Product/ProductDetailAPI.jsx
  moamoa/src/Pages/Product/ProductDetail.jsx
Labels: ✅ 완료, ♻️ 리팩토링

#253 [♻️refactor] 스플래쉬 페이지의 컴포넌트 분리 , 로고 애니메이션 변경
  moamoa/src/Assets/images/fireworks.svg
  moamoa/src/Components/Splash/LoginModal.jsx
  moamoa/src/Components/Splash/SplashLoginBtn.jsx
  moamoa/src/Components/Splash/SplashLogo.jsx
  moamoa/src/Pages/Product/ProductList.jsx
  moamoa/src/Pages/Profile/YourProfile.jsx
  moamoa/src/Pages/Splash/Landing.jsx
  moamoa/src/md.md
Labels: ✅ 완료, 🌈 스타일, ♻️ 리팩토링

#257 [♻️ Refactor] Fetch에서 Axios로 API 호출 코드 변경
  moamoa/src/API/Auth/JoinAPI.jsx
  moamoa/src/API/Auth/LoginAPI.jsx
  moamoa/src/API/Product/ProductDetailAPI.jsx
  moamoa/src/API/Product/ProductEditAPI.jsx
  moamoa/src/API/Product/ProductUploadAPI.jsx
  moamoa/src/API/Valid/AccountValidAPI.jsx
  moamoa/src/API/Valid/EmailValidAPI.jsx
  moamoa/src/Hooks/Sign/useJoin.jsx
  moamoa/src/Pages/Product/AddProduct.jsx
  moamoa/src/Pages/Product/EditProduct.jsx
Labels: ✅ 완료, ♻️ 리팩토링

#260 [♻️ Refactor] axios 인스턴스 추가
  moamoa/src/API/InstanceAPI.jsx
  moamoa/src/API/Post/PostAPI.jsx
  moamoa/src/API/Post/PostDetailAPI.jsx
  moamoa/src/Components/Modal/DeleteModal.jsx
  moamoa/src/Hooks/Sign/useLogin.jsx
  moamoa/src/Pages/Post/PostDetail.jsx
Labels: 🚀 진행중, ♻️ 리팩토링

#261 [♻️ Refactor] PostAPI 분리 및 axios 코드로 변경
  moamoa/src/API/Post/HeartCountDownAPI.jsx
  moamoa/src/API/Post/HeartCountUpAPI.jsx
  moamoa/src/API/Post/PostAPI.jsx
  moamoa/src/API/Post/PostDeleteAPI.jsx
  moamoa/src/API/Post/PostDetailAPI.jsx
  moamoa/src/Components/Home/HomePostCardList.jsx
  moamoa/src/Components/Modal/ReportModal.jsx
  moamoa/src/Components/Post/PostCardItem.jsx
  moamoa/src/Components/Post/PostCardList.jsx
  moamoa/src/Pages/Home/Home.jsx
Labels: ✅ 완료, ♻️ 리팩토링

#263 refactor: 컴포넌트 이름 변경
  moamoa/src/API/Profile/ProfileAPI.jsx
  moamoa/src/Components/Common/ArticleUserProfile.jsx
  moamoa/src/Components/Common/ProfileDetailPost.jsx
  moamoa/src/Components/Home/HomePostCardList.jsx
  moamoa/src/Components/Post/PostItem.jsx
  moamoa/src/Components/Post/PostList.jsx
  moamoa/src/Components/Post/PostMoreBtn.jsx
  moamoa/src/Pages/Home/Home.jsx
  moamoa/src/Pages/Post/PostDetail.jsx
  moamoa/src/Pages/Product/ProductDetail.jsx
Labels: 🚀 진행중, ♻️ 리팩토링

#264 [♻️Refactor] 축제 리스트 페이지 컴포넌트화, API GET 쿼리문 수정
  moamoa/src/API/Product/ProductListAPI.jsx
  moamoa/src/Components/ProductList/ProductListLoading.jsx
  moamoa/src/Components/ProductList/ProductOutput.jsx
  moamoa/src/Components/ProductList/TopNavigation.jsx
  moamoa/src/Pages/Home/Home.jsx
  moamoa/src/Pages/Product/ProductList.jsx
  moamoa/src/Recoil/ProductTypeStateAtom.jsx
Labels: ✅ 완료

#265 [♻️ Refactor] 게시글 목록 컴포넌트 통합
  moamoa/src/API/Post/PostAPI.jsx
  moamoa/src/Components/Common/ProfileDetailPost.jsx
  moamoa/src/Components/Home/HomePostCardList.jsx
  moamoa/src/Components/Home/HomePostMoreBtn.jsx
  moamoa/src/Components/Post/PostItem.jsx
  moamoa/src/Components/Post/PostList.jsx
  moamoa/src/Components/Post/PostMoreBtn.jsx
  moamoa/src/Components/Post/YourPostMoreBtn.jsx
  moamoa/src/Pages/Home/Home.jsx
  moamoa/src/Pages/Home/HomeSearch.jsx
Labels: 🚀 진행중, ♻️ 리팩토링
