Repository FRONTENDSCHOOL7/final-18-moamoa, pull requests merged in 2023-10, with the labels that each got.

#21 [✨ Feature] 라우터 초기세팅 입니다.
  .github/ISSUE_TEMPLATE/기능구현-재웅.md
  moamoa/Components/Landings.jsx
  moamoa/GlobalStyle.jsx
  moamoa/Pages/Landing.jsx
  moamoa/Router/AppRoutes.js
  moamoa/package-lock.json
  test.html
Labels: 📝 문서변경, ✨ 기능추가, 🎉시작

#25 [✨ Feature] 회원 가입, 로그인, 상품 등록 페이지 구현
  README.md
  moamoa/package-lock.json
  moamoa/package.json
  moamoa/public/index.html
  moamoa/src/Assets/icons/icon-arrow-left.svg
  moamoa/src/GlobalStyle.jsx
  moamoa/src/Pages/AddProduct.jsx
  moamoa/src/Pages/Join.jsx
  moamoa/src/Pages/Login.jsx
  moamoa/src/Recoil/EventCategory.jsx
  moamoa/src/Recoil/EventState.jsx
  moamoa/src/Recoil/JoinState.jsx
  moamoa/src/Recoil/UserToken.jsx
  moamoa/src/Router/AppRoutes.js
  moamoa/src/index.js
Labels: ✨ 기능추가, 🚀 진행중

#26 [✨ Feature] 프로필 페이지 구현
  moamoa/.eslintrc.json
  moamoa/src/App.js
  moamoa/src/Components/Landings.jsx
  moamoa/src/GlobalStyle.jsx
  moamoa/src/Pages/Landing.jsx
  moamoa/src/Pages/ProfileInfo.jsx
  moamoa/src/Router/AppRoutes.js
  test.html
Labels: ✨ 기능추가, 🚀 진행중

#27 [✨ Feature] 상품리스트 구현 중입니다.
  moamoa/.eslintrc.js
  moamoa/src/Pages/ProductDetail.jsx
  moamoa/src/Pages/ProductList.jsx
  moamoa/src/index.js
Labels: ✨ 기능추가, 🚀 진행중

#31 [✨ Feature] 상품 상세페이지 구현
  moamoa/.env
  moamoa/src/App.js
  moamoa/src/Pages/ProductDetail.jsx
  moamoa/src/Router/AppRoutes.js
Labels: ✨ 기능추가

#34 [✨ Feature] 프로필 수정 페이지 마크업 및 기능 구현
  moamoa/.eslintrc.json
  moamoa/src/Pages/EditProfile.jsx
  moamoa/src/Pages/ProfileInfo.jsx
  moamoa/src/Router/AppRoutes.js
Labels: ✨ 기능추가, 🎉시작

#35 [🌈 Style] 스플래시 화면 구현했습니다.
  moamoa/src/App.js
  moamoa/src/Assets/images/Bluemoa.png
  moamoa/src/Assets/images/Festival.svg
  moamoa/src/Assets/images/Logo.png
  moamoa/src/Assets/images/fireworks.svg
  moamoa/src/Assets/images/google.png
  moamoa/src/Assets/images/kakao.png
  moamoa/src/Assets/images/naver.png
  moamoa/src/GlobalStyle.jsx
  moamoa/src/Pages/AddProduct.jsx
  moamoa/src/Pages/Landing.jsx
  moamoa/src/Router/AppRoutes.js
  moamoa/src/fonts.css
Labels: 🚀 진행중, 🌈 스타일

#37 [✨ Feature] 상품 등록 페이지 기능 수정
  moamoa/src/Pages/AddProduct.jsx
Labels: ✨ 기능추가, 🚀 진행중

#41 [🔧 Fix] App.js 파일과 AddProduct 파일 오류 수정
  moamoa/src/App.js
  moamoa/src/Pages/AddProduct.jsx
Labels: 🚨에러발견, ✅ 완료

#42 [✨ Feature] Home 페이지 구현
  moamoa/src/Components/Common/PostCard.jsx
  moamoa/src/Pages/AddProduct.jsx
  moamoa/src/Pages/Home.jsx
  moamoa/src/Pages/PostDetail.jsx
  moamoa/src/Pages/ProductDetail.jsx
  moamoa/src/Pages/ProfileInfo.jsx
  moamoa/src/Router/AppRoutes.js
Labels: ✨ 기능추가

#49 📂Rename: 중복 폴더 삭제
  moamoa/src/Pages/AddPost.jsx
  moamoa/src/Pages/Home.jsx
Labels: 🗑️ 삭제, ✅ 완료

#51 [🔧 Fix] AppRoutes.js 파일의 ESLint 오류 수정
  moamoa/src/Router/AppRoutes.js
Labels: 🚨에러발견, ✅ 완료

#53 [✨ Feature] 게시글 작성 페이지 마크업 및 구현
  moamoa/src/Pages/Post/UploadPost.jsx
Labels: ✨ 기능추가

#54 [✨ Feature] Home 페이지 구현
  moamoa/src/Pages/Home/Home.jsx
Labels: ✨ 기능추가, ✅ 완료

#56 [✨ Feature] 이메일로 로그인 페이지 기능 추가
  moamoa/src/Pages/Login/Login.jsx
Labels: ✨ 기능추가, ✅ 완료

#57 [✨ Feature] 상세 프로필 페이지 기능 추가
  moamoa/src/Pages/Login/Login.jsx
  moamoa/src/Pages/Post/UploadPost.jsx
  moamoa/src/Pages/PostDetail.jsx
  moamoa/src/Pages/Profile/EditProfile.jsx
  moamoa/src/Pages/Profile/YourProfile.jsx
Labels: ✨ 기능추가, 🚀 진행중

#67 [📂 Rename] Recoil 폴더 안 파일명 변경 & 파일 삭제
  moamoa/src/Recoil/EventCategory.jsx
  moamoa/src/Recoil/EventState.jsx
  moamoa/src/Recoil/JoinState.jsx
  moamoa/src/Recoil/PostState.jsx
  moamoa/src/Recoil/UserToken.jsx
  moamoa/src/Recoil/eventTypeAtom.jsx
  moamoa/src/Recoil/followPostAtom.jsx
  moamoa/src/Recoil/userTokenAtom.jsx
  moamoa/src/Recoil/userTypeAtom.jsx
Labels: 🗑️ 삭제, 🔧 수정요청

#69 [🔧 Fix] Recoil 파일명 변경으로 인한 컴파일 에러 수정
  moamoa/src/Pages/Home/Home.jsx
  moamoa/src/Pages/Join/Join.jsx
  moamoa/src/Pages/Login/Login.jsx
  moamoa/src/Pages/Post/PostDetail.jsx
  moamoa/src/Pages/Post/UploadPost.jsx
  moamoa/src/Pages/Product/AddProduct.jsx
  moamoa/src/Pages/Product/ProductList.jsx
  moamoa/src/Pages/Profile/EditProfile.jsx
  moamoa/src/Pages/Profile/YourProfile.jsx
Labels: 🚨에러발견, ✅ 완료

#72 [🌈 Style] 상품 리스트 이미지 스타일 컴포넌트 구현했습니다.
  moamoa/.eslintrc.js
  moamoa/package-lock.json
  moamoa/package.json
  moamoa/src/Components/Common/Header.jsx
  moamoa/src/Components/Common/ProductImgBox.jsx
  moamoa/src/Pages/Product/ProductList.jsx
Labels: ✨ 기능추가, 🚀 진행중, 🌈 스타일

#75 [🌈 Style]: 게시글 상세 스타일 적용 및 컴포넌트화
  .DS_Store
  moamoa/src/Assets/icons/heart-fill.svg
  moamoa/src/Assets/icons/heart.svg
  moamoa/src/Assets/icons/message-circle.svg
  moamoa/src/Assets/icons/s-icon-more-vertical.svg
  moamoa/src/Components/Common/MoreBtn.jsx
  moamoa/src/Components/Common/PostCard.jsx
  moamoa/src/Components/Common/PostCardUser.jsx
  moamoa/src/GlobalStyle.jsx
  moamoa/src/Pages/Home/Home.jsx
  moamoa/src/Pages/Post/PostDetail.jsx
Labels: 🌈 스타일

#76 🌈style : 컨테이너,헤더,버튼 컴포넌트 구현했습니다.
  moamoa/src/Assets/icons/icon-edit-fill.svg
  moamoa/src/Assets/icons/icon-edit.svg
  moamoa/src/Assets/icons/icon-festival-fill.svg
  moamoa/src/Assets/icons/icon-festival.svg
  moamoa/src/Assets/icons/icon-home-fill.svg
  moamoa/src/Assets/icons/icon-home.svg
  moamoa/src/Assets/icons/icon-message-fill.svg
  moamoa/src/Assets/icons/icon-message.svg
  moamoa/src/Assets/icons/icon-more.svg
  moamoa/src/Assets/icons/icon-search.svg
  moamoa/src/Assets/icons/icon-user-fill.svg
  moamoa/src/Assets/icons/icon-user.svg
  moamoa/src/Components/Common/Button.jsx
  moamoa/src/Components/Common/Container.jsx
  moamoa/src/Components/Common/Footer.jsx
  moamoa/src/Components/Common/GoBackbtn.jsx
  moamoa/src/Components/Common/Header.jsx
  moamoa/src/Components/Common/HeaderAddProduct.jsx
  moamoa/src/Components/Common/HeaderBasic.jsx
  moamoa/src/Components/Common/HeaderHome.jsx
  moamoa/src/Components/Common/HeaderProductList.jsx
  moamoa/src/Components/Common/HeaderSearch.jsx
  moamoa/src/Components/Common/ProductImgBox.jsx
  moamoa/src/Components/Landings.jsx
  moamoa/src/GlobalStyle.jsx
  moamoa/src/Pages/Product/ProductDetail.jsx
  moamoa/src/Pages/Product/ProductList.jsx
  moamoa/src/Pages/Splash/Landing.jsx
Labels: ✅ 완료, 🌈 스타일

#77 [✨ Feature] 상품 등록 페이지 기능 수정
  moamoa/src/Pages/Product/AddProduct.jsx
Labels: ✨ 기능추가, ✅ 완료

#80 ✨Feat: 남의프로필/내프로필 분리, 팔로우/언팔로우 버튼 기능 컴포넌트화, 프로필 디테일 페이지 공통 마크업 컴포넌트화
  moamoa/src/Components/Common/FollowButton.jsx
  moamoa/src/Components/Common/ProfileDetail.jsx
  moamoa/src/Pages/Profile/MyProfile.jsx
  moamoa/src/Pages/Profile/YourProfile.jsx
Labels: ✨ 기능추가, 🚀 진행중

#82 [🌈 Style] 홈 화면 스타일 적용 추가
  moamoa/src/Assets/icons/character-yellow.png
  moamoa/src/Components/Common/PostCard.jsx
  moamoa/src/Pages/Home/Home.jsx
  moamoa/src/Pages/Home/HomeFeed.jsx
Labels: 🌈 스타일

#84 [♻️ Refactor] API 모듈 분리화 작업
  moamoa/src/API/Auth/JoinAPI.jsx
  moamoa/src/API/Auth/LoginAPI.jsx
  moamoa/src/API/Img/UploadImageAPI.jsx
  moamoa/src/API/Product/ProductDetailAPI.jsx
  moamoa/src/API/Product/ProductEditAPI.jsx
  moamoa/src/API/Product/ProductUploadAPI.jsx
  moamoa/src/API/Valid/AccountValidAPI.jsx
  moamoa/src/API/Valid/EmailValidAPI.jsx
Labels: ♻️ 리팩토링

#85 [🌈 Style]Footer 구현했습니다.
  moamoa/src/Assets/icons/icon-festival.svg
  moamoa/src/Assets/icons/icon-post-fill.svg
  moamoa/src/Assets/icons/icon-post.svg
  moamoa/src/Assets/icons/icon-user.svg
  moamoa/src/Components/Common/Container.jsx
  moamoa/src/Components/Common/Footer.jsx
  moamoa/src/Components/Common/HeaderSearch.jsx
  moamoa/src/GlobalStyle.jsx
  moamoa/src/Pages/Home/Home.jsx
  moamoa/src/Pages/Product/ProductList.jsx
  moamoa/src/Router/AppRoutes.js
Labels: ✨ 기능추가, ✅ 완료, 🌈 스타일

#89 [♻️ Refactor] 회원가입(프로필 포함)과 이메일로 로그인 페이지 필수 기능 & 컴포넌트 리팩토링
  moamoa/src/Hooks/Sign/useJoin.jsx
  moamoa/src/Hooks/Sign/useLogin.jsx
  moamoa/src/Pages/Join/Join.jsx
  moamoa/src/Pages/Login/Login.jsx
  moamoa/src/Pages/Profile/SetProfile.jsx
  moamoa/src/Recoil/accountNameAtom.jsx
  moamoa/src/Recoil/isLoginAtom.jsx
Labels: ✨ 기능추가, ♻️ 리팩토링

#88 [✨ Feature/ 🌈 Style] 상품 상세페이지 렌더링 조건 추가 및 스타일 적용
  moamoa/src/Components/Common/Footer.jsx
  moamoa/src/Components/Common/HeaderBasic.jsx
  moamoa/src/Components/Common/PostCard.jsx
  moamoa/src/Components/Common/PostCardUser.jsx
  moamoa/src/Pages/Follow/FollowerList.jsx
  moamoa/src/Pages/Product/AskBtn.jsx
  moamoa/src/Pages/Product/ProductDetail.jsx
Labels: ✨ 기능추가, ✅ 완료, 🌈 스타일

#90 [✨ Feature] 프로필 상세 페이지 하단 내 게시물 목록 마크업 컴포넌트화
  moamoa/src/Components/Common/Footer.jsx
  moamoa/src/Components/Common/ProfileDetail.jsx
  moamoa/src/Components/Common/ProfileDetailPost.jsx
  moamoa/src/Pages/Profile/MyProfile.jsx
  moamoa/src/Pages/Profile/YourProfile.jsx
Labels: ✨ 기능추가, 🚀 진행중

#93 [🚨Bug] 상품리스트 이미지 렌더링 안되는 오류 해결
  moamoa/src/API/Product/ProductListAPI.jsx
  moamoa/src/Assets/icons/icon-festival-fill.svg
  moamoa/src/Assets/images/backgroundMoamoa.png
  moamoa/src/Components/Common/Container.jsx
  moamoa/src/Components/Common/HeaderProductList.jsx
  moamoa/src/GlobalStyle.jsx
  moamoa/src/Pages/Product/ProductList.jsx
Labels: ✅ 완료

#95 [✨ Feature] 상품 리스트 구현 축제,체험 구분 렌더링 빼고 구현
  moamoa/src/Components/Common/Container.jsx
  moamoa/src/Components/Common/Footer.jsx
  moamoa/src/GlobalStyle.jsx
  moamoa/src/Pages/Product/ProductList.jsx
Labels: ✨ 기능추가, ✅ 완료, 🌈 스타일

#99 [🔧 Fix] 회원가입 시 회원유형 선택 / 상품등록 시 행사유형 선택 기능 수정
  moamoa/src/API/Auth/JoinAPI.jsx
  moamoa/src/API/Product/ProductUploadAPI.jsx
  moamoa/src/Hooks/Sign/useJoin.jsx
  moamoa/src/Pages/Product/AddProduct.jsx
Labels: ✅ 완료

#101 [✨ Feature] 프로필 상세 페이지 기능 추가, 진행중인 행사목록 컴포넌트화, 판매자/개인계정 구분
  moamoa/src/Components/Common/PostCard.jsx
  moamoa/src/Components/Common/ProfileDetail.jsx
  moamoa/src/Components/Common/ProfileDetailPost.jsx
  moamoa/src/Components/Common/ProfileDetailProduct.jsx
  moamoa/src/Hooks/Sign/useLogin.jsx
  moamoa/src/Pages/Post/PostDetailTest.jsx
  moamoa/src/Pages/Profile/MyProfile.jsx
  moamoa/src/Pages/Profile/YourProfile.jsx
  moamoa/src/Recoil/userNameAtom.jsx
Labels: ✨ 기능추가, 🚀 진행중

#103 [🌈 Style]Followers 페이지 , Following 페이지 마크업 구현
  moamoa/src/Assets/images/followImg/child.jpg
  moamoa/src/Assets/images/followImg/concept.jpg
  moamoa/src/Assets/images/followImg/dog.jpg
  moamoa/src/Assets/images/followImg/fog.jpg
  moamoa/src/Assets/images/followImg/happy.jpg
  moamoa/src/Assets/images/followImg/human.jpg
  moamoa/src/Assets/images/followImg/water.jpg
  moamoa/src/Assets/images/followImg/woman.jpg
  moamoa/src/Assets/images/followImg/woman2.jpg
  moamoa/src/Components/Common/Button.jsx
  moamoa/src/Components/Common/FollowUser.jsx
  moamoa/src/Components/Common/FollowingUser.jsx
  moamoa/src/Components/Common/GoBackbtn.jsx
  moamoa/src/Components/Common/HeaderFollowingList.jsx
  moamoa/src/Components/Common/HeaderFollwerList.jsx
  moamoa/src/Components/Common/ProductImgBox.jsx
  moamoa/src/GlobalStyle.jsx
  moamoa/src/Pages/Follow/FollowerList.jsx
  moamoa/src/Pages/Follow/FollowingList.jsx
  moamoa/src/Router/AppRoutes.js
Labels: ✅ 완료, 🌈 스타일

#107 [✨ Feature] 프로필 수정 페이지, 게시글 등록 페이지 기능 추가
  moamoa/src/Pages/Post/UploadPost.jsx
  moamoa/src/Pages/Profile/EditProfile.jsx
Labels: ✨ 기능추가, ✅ 완료

#108 [🔧fix] Splash 화면에서 콘솔에 나오는 오류
  moamoa/src/Pages/Splash/Landing.jsx
Labels: ✅ 완료

#112 [✨ Feature / 🌈 Style] 댓글 기능 구현 및 스타일 적용
  moamoa/src/Components/Comment/AddCommentBtn.jsx
  moamoa/src/Components/Comment/Comment.jsx
  moamoa/src/Components/Comment/CommentItem.jsx
  moamoa/src/Components/Comment/timecalc.js
  moamoa/src/Components/Common/PostCard.jsx
  moamoa/src/Pages/Home/Home.jsx
  moamoa/src/Pages/Post/PostDetail.jsx
Labels: ✨ 기능추가, 🤡 도움요청, 🌈 스타일

#114 [✨ Feature] 게시글 수정 페이지 기능 구현, 게시글 등록 페이지 기능 추가
  moamoa/src/Pages/Post/EditPost.jsx
  moamoa/src/Pages/Post/UploadPost.jsx
Labels: ✨ 기능추가, ✅ 완료

#117 [✨ Feature] 사용자 프로필로 이동 기능 추가
  moamoa/src/Components/Common/PostCardUser.jsx
Labels: ✨ 기능추가

#123 [✨ Feature]: api 연결하여 팔로우,팔로잉 구현했습니다.
  moamoa/src/API/Follow/FollowerAPI.jsx
  moamoa/src/API/Follow/FollowingAPI.jsx
  moamoa/src/Components/Common/FollowUser.jsx
  moamoa/src/Components/Common/FollowingUser.jsx
  moamoa/src/Components/Common/GoBackbtn.jsx
  moamoa/src/Pages/Follow/FollowerList.jsx
  moamoa/src/Pages/Follow/FollowingList.jsx
  moamoa/src/Pages/Post/PostDetail.jsx
  moamoa/src/Pages/Splash/Landing.jsx
Labels: 🚨에러발견

#124 [ 🔧 Fix ] 마이페이지 PostCard 출력, 파일명 및 경로 변경
  moamoa/src/Components/Comment/AddCommentBtn.jsx
  moamoa/src/Components/Comment/Comment.jsx
  moamoa/src/Components/Comment/CommentItem.jsx
  moamoa/src/Components/Common/ProfileDetailPost.jsx
  moamoa/src/Components/Common/datecalc.js
  moamoa/src/Components/Post/PostCardItem.jsx
  moamoa/src/Components/Post/PostCardList.jsx
  moamoa/src/Components/Post/PostCardUser.jsx
  moamoa/src/Pages/Home/Home.jsx
  moamoa/src/Pages/Post/PostDetail.jsx
  moamoa/src/Pages/Product/EditProduct.jsx
  moamoa/src/Pages/Product/ProductDetail.jsx
  moamoa/src/Recoil/detailPostAtom.jsx
Labels: 🔧 수정완료

#127 [🌈 Style] 게시글 등록 페이지 디자인 작업
  moamoa/src/Assets/icons/x.svg
  moamoa/src/Assets/images/upload-file.png
  moamoa/src/Components/Common/Button.jsx
  moamoa/src/Components/Common/Container.jsx
  moamoa/src/Components/Common/Footer.jsx
  moamoa/src/Components/Common/HeaderAddProduct.jsx
  moamoa/src/Components/Common/HeaderHome.jsx
  moamoa/src/Components/Common/HeaderProductList.jsx
  moamoa/src/Components/Common/HeaderSearch.jsx
  moamoa/src/Pages/Home/HomeFeed.jsx
  moamoa/src/Pages/Post/UploadPost.jsx
  moamoa/src/Pages/Product/ProductList.jsx
Labels: ✅ 완료, 🌈 스타일

#130 [✨ Feature] 상품 수정 페이지 및 수정 기능 구현
  moamoa/src/API/Product/ProductDetailAPI.jsx
  moamoa/src/API/Product/ProductEditAPI.jsx
  moamoa/src/Pages/Product/AddProduct.jsx
  moamoa/src/Pages/Product/AskBtn.jsx
  moamoa/src/Pages/Product/EditProduct.jsx
  moamoa/src/Pages/Product/ProductDetail.jsx
Labels: ✨ 기능추가, ✅ 완료

#135 [✨ Feat/🌈 Style] 게시글 삭제 모달 추가 및 스타일 적용
  moamoa/src/Assets/icons/x.png
  moamoa/src/Components/Common/MoreBtn.jsx
  moamoa/src/Components/Modal/DeleteModal.jsx
  moamoa/src/Components/Modal/PostModal.jsx
  moamoa/src/Components/Modal/ReportModal.jsx
  moamoa/src/Components/Post/PostCardItem.jsx
  moamoa/src/Pages/Post/PostDetail.jsx
  moamoa/src/Pages/Post/PostDetailTest.jsx
  moamoa/src/Recoil/postModalDelAtom.jsx
  moamoa/src/Recoil/postModalOpenAtom.jsx
  moamoa/src/Router/AppRoutes.js
Labels: ✨ 기능추가, 🌈 스타일
