Repository FRONTENDSCHOOL7/final-18-moamoa, pull requests merged in 2023-12, with the labels that each got.

#272 [♻️ Refactor] 검색 페이지 컴포넌트 분리와 로딩 스피너를 스켈레톤으로 변경
  moamoa/package-lock.json
  moamoa/package.json
  moamoa/src/Components/Search/NotFound.jsx
  moamoa/src/Components/Search/SearchResultBox.jsx
  moamoa/src/Components/Search/SearchSkeleton.jsx
  moamoa/src/Components/Search/UserId.jsx
  moamoa/src/Hooks/Search/useDebounce.jsx
  moamoa/src/Pages/Product/ProductList.jsx
  moamoa/src/Pages/Search/Loader.jsx
  moamoa/src/Pages/Search/Search.jsx
Labels: 🔧 수정, 🌈 스타일, ♻️ 리팩토링

#274 [♻️ Refactor] Header 컴포넌트 Home 이동 경로 추가
  moamoa/src/Assets/icons/icon-arrow-left.svg
  moamoa/src/Assets/images/MOAMOA.png
  moamoa/src/Components/Common/ChatMoreBtn.jsx
  moamoa/src/Components/Common/GoBackbtn.jsx
  moamoa/src/Components/Common/HeaderBasic.jsx
  moamoa/src/Components/Common/HeaderChat.jsx
  moamoa/src/Components/Common/HeaderHome.jsx
  moamoa/src/Components/Common/HeaderKebab.jsx
  moamoa/src/Components/Common/HeaderProductList.jsx
  moamoa/src/Pages/Home/Home.jsx
Labels: ✨ 기능추가, ♻️ 리팩토링

#285 [✨ Feature] 행사 상세페이지 행사 장소 지도 추가
  moamoa/.env
  moamoa/.gitignore
  moamoa/public/index.html
  moamoa/src/Assets/images/mono_moa.png
  moamoa/src/Components/Common/ArticleUserProfile.jsx
  moamoa/src/Components/Common/Footer.jsx
  moamoa/src/Components/Common/HeaderHome.jsx
  moamoa/src/Components/Post/PostItem.jsx
  moamoa/src/Components/Post/PostList.jsx
  moamoa/src/Components/Product/FestaMap.jsx
  moamoa/src/Components/Product/ProductContents.jsx
  moamoa/src/Components/Product/ProductListLoading.jsx
  moamoa/src/Components/Product/ProductOutput.jsx
  moamoa/src/Components/Product/TopNavigation.jsx
  moamoa/src/Pages/Home/Home.jsx
  moamoa/src/Pages/Product/ProductDetail.jsx
  moamoa/src/Pages/Product/ProductList.jsx
Labels: ✨ 기능추가, ✅ 완료

#287 [🚨Bug] .gitignore 오류 해결
  moamoa/.env
  moamoa/src/API/Post/PostAPI.jsx
  moamoa/src/Pages/Home/Home.jsx
  moamoa/src/Recoil/detailPostAtom.jsx
  moamoa/src/Recoil/moreBtnPordAtom.jsx
  moamoa/src/Recoil/moreBtnPostAtom.jsx
  moamoa/src/Recoil/postsAtom.jsx
Labels: ✅ 완료

#289 [🌈Style/#284] 스플래시 애니메이션 변경
  moamoa/src/Components/Common/HeaderKebab.jsx
  moamoa/src/Components/Splash/SplashLogo.jsx
  moamoa/src/Pages/Product/ProductDetail.jsx
Labels: 💡 질문, ✅ 완료, 🌈 스타일

#292 [✨ Feature] 테스트 계정으로 로그인 기능 추가
  moamoa/src/Hooks/Auth/useLogin.jsx
  moamoa/src/Pages/Auth/Login.jsx
Labels: ✨ 기능추가, ✅ 완료

#294 [♻️ Refactor] Lodash 적용 & 각 페이지에서 이미지 업로드 시 중복 코드 제거
  moamoa/package-lock.json
  moamoa/package.json
  moamoa/src/Hooks/Auth/useSignUp.jsx
  moamoa/src/Hooks/Common/useImageUpload.jsx
  moamoa/src/Pages/Product/ProductAdd.jsx
  moamoa/src/Pages/Product/ProductEdit.jsx
  moamoa/src/Utils/handleUploadImage.jsx
  moamoa/src/Utils/updateInputState.jsx
Labels: ✅ 완료, ♻️ 리팩토링

#297 [✨ Feature] 행사 등록(상품 등록) 시 행사 장소 추가
  moamoa/src/Components/Common/ProductSharedStyle.jsx
  moamoa/src/Pages/Product/ProductAdd.jsx
  moamoa/src/Pages/Product/ProductEdit.jsx
Labels: ✨ 기능추가, ✅ 완료

#300 [♻️ Refactor /✨ Feature] 상품 등록 및 수정 코드 리팩토링, 상품 수정 페이지 행사 장소 추가
  moamoa/src/Hooks/Product/useDateValidation.jsx
  moamoa/src/Pages/Product/ProductAdd.jsx
  moamoa/src/Pages/Product/ProductEdit.jsx
Labels: ✨ 기능추가, ✅ 완료, ♻️ 리팩토링

#302 [🔧 Fix] post 데이터 recoil 사용한 코드로 변경
  moamoa/src/Components/Post/PostList.jsx
  moamoa/src/Pages/Home/Home.jsx
Labels: 🤡 도움요청, 🔧 수정

#304 [♻️ Refactor] 상품 등록과 상품 수정 컴포넌트 간에 중복 로직 분리
  moamoa/src/Components/Product/ProductForm.jsx
  moamoa/src/Hooks/Auth/useSignUp.jsx
  moamoa/src/Hooks/Product/useProductData.jsx
  moamoa/src/Hooks/Product/useSubmitProductForm.jsx
  moamoa/src/Pages/Product/ProductAdd.jsx
  moamoa/src/Pages/Product/ProductEdit.jsx
  moamoa/src/Utils/handleUploadImage.jsx
Labels: ✅ 완료, ♻️ 리팩토링

#305 [♻️ Refactor] 상품 상세 페이지 행사 장소 추가
  moamoa/src/Components/Modal/DeleteModal.jsx
  moamoa/src/Components/Modal/FooterModal.jsx
  moamoa/src/Components/Post/PostMoreBtn.jsx
  moamoa/src/Components/Product/ProductContents.jsx
  moamoa/src/Pages/Product/ProductEdit.jsx
Labels: ✅ 완료, ♻️ 리팩토링

#307 [♻️ Refactor] 웹 접근성 고려한 사용자 위주의 UI/UX 코드로 수정
  moamoa/src/Components/Common/AuthFormStyle.jsx
  moamoa/src/Components/Common/FormLoginAndJoin.jsx
  moamoa/src/Components/Common/Header.jsx
  moamoa/src/Components/Common/HeaderComponents.jsx
  moamoa/src/Components/Common/ProductFormStyle.jsx
  moamoa/src/Components/Common/ProductSharedStyle.jsx
  moamoa/src/Components/Product/ProductForm.jsx
  moamoa/src/Hooks/Auth/useLogin.jsx
  moamoa/src/Pages/Auth/Login.jsx
  moamoa/src/Pages/Auth/SignUp.jsx
  moamoa/src/Pages/Product/ProductAdd.jsx
  moamoa/src/Pages/Product/ProductEdit.jsx
Labels: ✅ 완료, ♻️ 리팩토링

#311 [🔧 Fix] 상품(행사)저장 버튼 위치 조정
  moamoa/src/Components/Common/ProductFormStyle.jsx
Labels: ✅ 완료, 🔧 수정

#313 [🔧 Fix] 폰트 크기와 자간 수정
  moamoa/src/Components/Common/AuthFormStyle.jsx
  moamoa/src/Components/Common/ProductFormStyle.jsx
  moamoa/src/Components/Product/ProductForm.jsx
  moamoa/src/Hooks/Product/useDateValidation.jsx
  moamoa/src/Pages/Auth/Login.jsx
  moamoa/src/Pages/Auth/SignUp.jsx
Labels: ✅ 완료, 🔧 수정

#315 [♻️ Refactor / 🔧 Fix] 페이지 리팩토링 및 프로필 상세 페이지 UI 수정
  moamoa/src/API/Follow/FollowAPI.jsx
  moamoa/src/API/Post/PostAPI.jsx
  moamoa/src/API/Product/ProductAPI.jsx
  moamoa/src/API/Profile/FollowAPI.jsx
  moamoa/src/API/Profile/GetYourinfoAPI.jsx
  moamoa/src/API/Profile/ProfileAPI.jsx
  moamoa/src/API/Profile/UnFollowAPI.jsx
  moamoa/src/Components/Common/ProfileDetailProduct.jsx
  moamoa/src/Components/Profile/ConfirmDelModal.jsx
  moamoa/src/Components/Profile/FollowButton.jsx
  moamoa/src/Components/Profile/MyProductClick.jsx
  moamoa/src/Components/Profile/PostCount.jsx
  moamoa/src/Components/Profile/ProfileDetail.jsx
  moamoa/src/Components/Profile/ProfileDetailPost.jsx
  moamoa/src/Components/Profile/ProfileDetailProduct.jsx
  moamoa/src/Pages/Post/EditPost.jsx
  moamoa/src/Pages/Post/UploadPost.jsx
  moamoa/src/Pages/Profile/EditProfile.jsx
  moamoa/src/Pages/Profile/MyProfile.jsx
  moamoa/src/Pages/Profile/YourProfile.jsx
Labels: 🔧 수정, 🚀 진행중, ♻️ 리팩토링

#320 [🔧 Fix/ 🌈 Style]축제&체험 리스트 페이지 스타일 수정, 스플래쉬 로고 시간 수정,이미지 alt 삽입
  moamoa/src/Components/Common/ChatMoreBtn.jsx
  moamoa/src/Components/Common/ChatPhoto.jsx
  moamoa/src/Components/Common/Container.jsx
  moamoa/src/Components/Common/FollowingUser.jsx
  moamoa/src/Components/Splash/LoginModal.jsx
  moamoa/src/Components/Splash/SplashLoginBtn.jsx
  moamoa/src/Pages/Chat/ChatRoomAccount.jsx
  moamoa/src/Pages/Chat/ChatRoomDarkHorse.jsx
  moamoa/src/Pages/Chat/ChatRoomKim.jsx
  moamoa/src/Pages/Chat/ChatRoomSumiDad.jsx
  moamoa/src/Pages/Product/ProductList.jsx
Labels: ✅ 완료, 🔧 수정, 🌈 스타일, ♻️ 리팩토링

#322 [♻️ Refactor]행사&축제 페이지 코드 컴포넌트 분리와 행사 기간 시맨틱 태그 변경
  moamoa/src/Components/Product/ProductOutput.jsx
  moamoa/src/Components/Product/filterActive.js
  moamoa/src/Components/Product/formatEventDate.js
Labels: ✨ 기능추가, 🔧 수정, 🚀 진행중, ♻️ 리팩토링

#328 [🌈 Style]상품&축제 리스트의 열을 1 줄로 변경
  moamoa/src/Components/Common/ProductImgBox.jsx
  moamoa/src/Components/Product/ProductOutput.jsx
Labels: 🔧 수정, 🌈 스타일

#329 [♻️ Refactor] 모달, 댓글 컴포넌트 코드 정리 및 API 분리, 컴포넌트 통합
  .vscode/launch.json
  moamoa/.vscode/launch.json
  moamoa/package-lock.json
  moamoa/package.json
  moamoa/src/API/Comment/CommnetAPI.jsx
  moamoa/src/API/Comment/CommnetDeleteAPI.jsx
  moamoa/src/API/Post/PostAPI.jsx
  moamoa/src/Components/Comment/Comment.jsx
  moamoa/src/Components/Comment/CommentAddBtn.jsx
  moamoa/src/Components/Comment/CommentDelModal.jsx
  moamoa/src/Components/Comment/CommentItem.jsx
  moamoa/src/Components/Comment/CommentReportModal.jsx
  moamoa/src/Components/Common/HeaderKebab.jsx
  moamoa/src/Components/Common/ProfileDetailProduct.jsx
  moamoa/src/Components/Modal/AlertModal.jsx
  moamoa/src/Components/Modal/DeleteModal.jsx
  moamoa/src/Components/Modal/HeaderMoreBtnModal.jsx
  moamoa/src/Components/Modal/LogoutConfirmModal.jsx
  moamoa/src/Components/Modal/LogoutModal.jsx
  moamoa/src/Components/Modal/MoreBtnModal.jsx
  moamoa/src/Components/Modal/ReportAlert.jsx
  moamoa/src/Components/Modal/ReportModal.jsx
  moamoa/src/Components/Post/PostItem.jsx
  moamoa/src/Components/Post/PostList.jsx
  moamoa/src/Components/Post/PostMoreBtn.jsx
  moamoa/src/Components/Product/AskBtn.jsx
  moamoa/src/Components/Product/FestaMap.jsx
  moamoa/src/Components/Profile/ConfirmDelModal.jsx
  moamoa/src/Pages/Home/Home.jsx
  moamoa/src/Pages/Home/observe.js
  moamoa/src/Pages/Product/ProductDetail.jsx
  moamoa/src/Recoil/postsAtom.jsx
Labels: ♻️ 리팩토링

#330 [🌈 Style]검색 실패 이미지 중앙 배치, 뒤로가기 버튼 밀림 수정, 유저 검색 iuput 크기 수정, input 포커스 보더색 변경
  moamoa/src/Components/Common/HeaderComponents.jsx
  moamoa/src/Components/Search/NotFound.jsx
  moamoa/src/Pages/Search/Search.jsx
Labels: ✅ 완료, 🔧 수정, 🌈 스타일

#331 [✨ Feature] 이미지 업로드 시 크롭 기능 추가
  moamoa/package-lock.json
  moamoa/package.json
  moamoa/src/Components/Common/ProductFormStyle.jsx
  moamoa/src/Components/Modal/ImageCropModal.jsx
  moamoa/src/Components/Product/ProductForm.jsx
  moamoa/src/Hooks/Auth/useSignUp.jsx
  moamoa/src/Hooks/Product/useProductData.jsx
  moamoa/src/Hooks/Product/useSubmitProductForm.jsx
  moamoa/src/Pages/Auth/SignUp.jsx
  moamoa/src/Pages/Post/EditPost.jsx
  moamoa/src/Pages/Post/UploadPost.jsx
  moamoa/src/Pages/Product/ProductAdd.jsx
  moamoa/src/Pages/Product/ProductEdit.jsx
  moamoa/src/Pages/Profile/EditProfile.jsx
  moamoa/src/Utils/cropImage.js
  moamoa/src/Utils/handleUploadImage.jsx
Labels: ✨ 기능추가, ✅ 완료

#332 [🌈 Style] 1줄로 바꾼 상품리스트의 스켈레톤 UI 수정
  moamoa/src/Components/Product/ProductListSkeleton.jsx
  moamoa/src/Components/Product/ProductOutput.jsx
  moamoa/src/Pages/Product/ProductList.jsx
Labels: ✅ 완료, 🔧 수정, 🌈 스타일

#333 [♻️ Refactor] ProductAPI,FollowAPI로 productListAPI,Follower&FollowingAPI 병합
  moamoa/src/API/Follow/FollowAPI.jsx
  moamoa/src/API/Follow/FollowerAPI.jsx
  moamoa/src/API/Follow/FollowingAPI.jsx
  moamoa/src/API/Product/ProductAPI.jsx
  moamoa/src/API/Product/ProductListAPI.jsx
  moamoa/src/Pages/Follow/FollowerList.jsx
  moamoa/src/Pages/Follow/FollowingList.jsx
  moamoa/src/Pages/Product/ProductList.jsx
Labels: ✅ 완료, ♻️ 리팩토링

#335 [🔧 Fix / ♻️ Refactor] 상품 등록, 상품 수정 폼 미입력 정보 확인 요청 방식 수정 / 공통 로직 추출
  moamoa/src/Components/Common/ProductFormStyle.jsx
  moamoa/src/Components/Modal/RequiredInputModal.jsx
  moamoa/src/Components/Product/ProductForm.jsx
  moamoa/src/Hooks/Product/useProductData.jsx
  moamoa/src/Pages/Product/ProductAdd.jsx
  moamoa/src/Pages/Product/ProductEdit.jsx
Labels: ✅ 완료, 🔧 수정
