Repository FRONTENDSCHOOL7/final-18-moamoa, pull requests merged in 2024-02, with the labels that each got.

#374 [♻️ Refactor] 스플래시 페이지 반응형 디자인 수정
  src/Components/Splash/SplashLoginBtn.jsx
  src/Components/Splash/SplashStyle.js
  src/Pages/Splash/SplashStyle.js
Labels: ♻️ 리팩토링

#376 [♻️ Refactor / 🌈 Style] SignUp/행사 상세/homeSearch 반응형 ui 구현
  src/Assets/icons/icon-email.svg
  src/Assets/icons/icon-lock.svg
  src/Assets/images/upload-file.png
  src/Components/Common/Header/HeaderStyle.js
  src/Components/Common/Myfollowings.jsx
  src/Pages/Auth/AuthStyle.jsx
  src/Pages/Auth/SignUp.jsx
  src/Pages/Home/Home.jsx
  src/Pages/Home/HomeStyle.jsx
  src/Pages/Product/ProductStyle.js
Labels: ✅ 완료, 🌈 스타일, ♻️ 리팩토링

#378 [♻️ Refactor/ 🌈 Style] NavBar hover UI 수정
  src/Components/Common/Header/HeaderKebab.jsx
  src/Components/Common/Header/HeaderStyle.js
  src/Components/Common/NavBar.jsx
  src/Components/Common/NavBarStyle.js
  src/Pages/Chat/ChatList.jsx
  src/Pages/Follow/FollowerList.jsx
  src/Pages/Follow/FollowingList.jsx
  src/Pages/Home/Home.jsx
  src/Pages/Post/PostDetail.jsx
  src/Pages/Post/PostDetailStyle.jsx
  src/Pages/Product/ProductDetail.jsx
  src/Pages/Product/ProductList.jsx
  src/Pages/Profile/MyProfile.jsx
  src/Pages/Profile/YourProfile.jsx
  src/Pages/Search/Search.jsx
Labels: ✅ 완료, 🌈 스타일

#380 [♻️ Refactor / 🌈 Style] 장소 추천, Myfollowings skeleton ui 추가
  src/Components/Common/Myfollowings.jsx
  src/Components/Common/RecommendPlace.jsx
  src/Components/Skeleton/MyFollowingSkeleton.jsx
  src/Components/Skeleton/RecommendSkeleton.jsx
Labels: ✅ 완료, ♻️ 리팩토링

#381 [🔧 Fix]로고 텍스트 오타 수정,회원가입과 같은 위치로 로고 위치 수정
  src/Components/Splash/SplashLogo.jsx
  src/Components/Splash/SplashStyle.js
  src/Pages/Splash/SplashStyle.js
Labels: 🔧 수정

#382 [♻️ Refactor / 🌈 Style] 프로필 상세 페이지 반응형 작업 -->
  package-lock.json
  package.json
  src/Assets/icons/message-btn-desktop.svg
  src/Assets/icons/message-btn.svg
  src/Assets/icons/share-btn-desktop.svg
  src/Assets/icons/share-btn.svg
  src/Components/Common/Container.jsx
  src/Components/Profile/ConfirmDelModal.jsx
  src/Components/Profile/FollowButton.jsx
  src/Components/Profile/MyProductClick.jsx
  src/Components/Profile/MyProductModal.jsx
  src/Components/Profile/MyProductModalStyle.js
  src/Components/Profile/PostCount.jsx
  src/Components/Profile/ProfileDetail.jsx
  src/Components/Profile/ProfileDetailPost.jsx
  src/Components/Profile/ProfileDetailProduct.jsx
  src/Components/Profile/ProfileStyle.js
  src/GlobalStyle.jsx
  src/Pages/Home/HomeSearch.jsx
  src/Pages/Post/EditPost.jsx
  src/Pages/Post/UploadEditPostStyle.jsx
  src/Pages/Post/UploadPost.jsx
  src/Pages/Profile/EditProfile.jsx
  src/Pages/Profile/MyProfile.jsx
  src/Pages/Profile/ProfileSkeleton.jsx
  src/Pages/Profile/ProfileStyle.js
  src/Pages/Profile/YourProfile.jsx
Labels: 🌈 스타일, ♻️ 리팩토링

#383 [♻️ Refactor] 로그인 페이지 반응형 ui
  src/Pages/Auth/Login.jsx
  src/Pages/Auth/TabletSplash.jsx
Labels: 🌈 스타일, ♻️ 리팩토링

#385 [♻️ Refactor x/ 🌈 Style] 프로필 상세 페이지 반응형 작업
  src/API/Profile/ProfileAPI.jsx
  src/Components/Common/Button.jsx
  src/Components/Common/Header/HeaderStyle.js
  src/Components/Profile/ProfileStyle.js
  src/Pages/Profile/EditProfile.jsx
  src/Pages/Profile/EditProfileStyle.js
Labels: 🌈 스타일, ♻️ 리팩토링

#388 [🔧 Fix/ 🌈 Style] 반응형 splash 위치 조정
  src/Pages/Auth/AuthStyle.jsx
  src/Pages/Auth/Login.jsx
  src/Pages/Auth/SignUp.jsx
  src/Pages/Auth/TabletSplash.jsx
Labels: ✅ 완료, 🔧 수정

#389 [♻️ Refactor] 검색,채팅 리스트에 장소추천,my following 추가
  src/Components/Common/Header/HeaderStyle.js
  src/Components/Search/SearchStyle.js
  src/Pages/Chat/ChatList.jsx
  src/Pages/Chat/ChatStyle.js
  src/Pages/Product/ProductStyle.js
  src/Pages/Search/Search.jsx
  src/Pages/Search/SearchStyle.js
Labels: ✨ 기능추가, ♻️ 리팩토링

#390 [♻️ Refactor ]팔로우 페이지 반응형 ui 구현,시맨틱 태그로 변경
  src/Components/Common/FollowStyle.jsx
  src/Components/Common/FollowUser.jsx
  src/Components/Common/FollowingUser.jsx
  src/Components/Common/Header/HeaderStyle.js
  src/Components/Common/NavBarStyle.js
  src/Components/Product/ProductStyle.js
  src/Components/Search/SearchStyle.js
  src/Pages/Chat/ChatStyle.js
  src/Pages/Follow/FollowStyle.js
  src/Pages/Search/SearchStyle.js
Labels: 🌈 스타일, ♻️ 리팩토링

#391 [🔧 Fix]NavBar의 a 태그 css 수정, a 태그 cursor:pointer GlobalStyle.jsx 적용
  src/Components/Common/NavBarStyle.js
  src/GlobalStyle.jsx
Labels: 🔧 수정

#392 [♻️ Refactor / 🌈 Style] 게시글 작성/수정 페이지 반응형 작업
  src/Pages/Post/EditPost.jsx
  src/Pages/Post/UploadEditPostStyle.jsx
  src/Pages/Post/UploadPost.jsx
Labels: 🌈 스타일, ♻️ 리팩토링

#393 [♻️ Refactor / 🌈 Style] 행사 등록/수정 페이지 반응형 작업
  src/Components/Product/ProductFormStyle.jsx
  src/Components/Profile/ProfileDetailProduct.jsx
  src/GlobalStyle.jsx
  src/Pages/Post/EditPost.jsx
  src/Pages/Post/UploadEditPostStyle.jsx
  src/Pages/Post/UploadPost.jsx
  src/Pages/Product/ProductAdd.jsx
  src/Pages/Product/ProductAddEditStyle.js
  src/Pages/Product/ProductEdit.jsx
  src/Pages/Profile/EditProfile.jsx
  src/Pages/Profile/EditProfileStyle.js
  src/Pages/Profile/ProfileStyle.js
Labels: 🌈 스타일, ♻️ 리팩토링

#395 [♻️ Refactor / 🌈 Style] 채팅방 페이지 반응형 구현
  src/Pages/Chat/ChatRoomAccount.jsx
  src/Pages/Chat/ChatRoomDarkHorse.jsx
  src/Pages/Chat/ChatRoomKim.jsx
  src/Pages/Chat/ChatRoomSumiDad.jsx
  src/Pages/Chat/ChatStyle.js
Labels: 🌈 스타일, ♻️ 리팩토링

#396 [♻️ Refactor] 불필요한 코드 제거
  src/API/Post/PostAPI.jsx
  src/Components/Common/Myfollowings.jsx
  src/Pages/Auth/AuthStyle.jsx
  src/Pages/Home/Home.jsx
Labels: 🗑️ 삭제

#397 [🔧 Fix]로그아웃 후 navigate 경로 수정
  src/Components/Common/Header/HeaderKebab.jsx
  src/Components/Common/NavBar.jsx
Labels: 🔧 수정

#399 [♻️ Refactor / 🌈 Style] 모바일 화면 반응형 작업
  src/Components/Comment/Comment.jsx
  src/Components/Common/ArticleUserProfile.jsx
  src/Components/Common/Container.jsx
  src/Components/Common/FollowStyle.jsx
  src/Components/Common/Header/HeaderKebab.jsx
  src/Components/Common/Header/HeaderStyle.js
  src/Components/Common/NavBarStyle.js
  src/Components/Post/PostContents.jsx
  src/Components/Product/ProductContents.jsx
  src/Components/Product/ProductFormStyle.jsx
  src/Components/Product/ProductStyle.js
  src/Components/Profile/ProfileStyle.js
  src/Components/Search/SearchStyle.js
  src/Components/Skeleton/MyProfileSkeleton.jsx
  src/Components/Skeleton/ProfileDetailProductSkeleton.jsx
  src/Components/Skeleton/ProfileDetailSkeleton.jsx
  src/Components/Skeleton/YourProfileSkeleton.jsx
  src/Components/Splash/SplashStyle.js
  src/GlobalStyle.jsx
  src/Pages/Chat/ChatStyle.js
  src/Pages/Follow/FollowStyle.js
  src/Pages/Post/PostDetail.jsx
  src/Pages/Post/PostDetailStyle.jsx
  src/Pages/Post/UploadEditPostStyle.js
  src/Pages/Product/ProductAddEditStyle.js
  src/Pages/Product/ProductStyle.js
  src/Pages/Profile/MyProfile.jsx
  src/Pages/Profile/ProfileSkeleton.jsx
  src/Pages/Profile/YourProfile.jsx
  src/Pages/Search/Search.jsx
  src/Pages/Search/SearchStyle.js
  src/Pages/Splash/SplashStyle.js
Labels: 🌈 스타일, ♻️ 리팩토링

#402 [♻️ Refactor / 🌈 Style] 댓글 입력, 행사 상세페이지 유저 프로필 ui 수정
  src/Components/Comment/Comment.jsx
  src/Components/Common/ArticleUserProfile.jsx
  src/Components/Product/ProductContents.jsx
  src/Pages/Product/ProductStyle.js
Labels: ✅ 완료, ♻️ 리팩토링

#406 [♻️ Refactor ]축제 리스트 IntersectionObserver로 관찰하여 무한스크롤 구현
  src/Components/Product/ProductOutput.jsx
Labels: ♻️ 리팩토링

#404 [♻️ Refactor] 사파리 ui 깨짐 위치 조정, 폴더 구조 정리
  src/Components/Button/Button.jsx
  src/Components/Button/GoBackbtn.jsx
  src/Components/Button/HomeBtn.jsx
  src/Components/Button/MoreBtn.jsx
  src/Components/Button/SearchBtn.jsx
  src/Components/Chat/ChatMoreBtn.jsx
  src/Components/Chat/ChatPhoto.jsx
  src/Components/Follow/FollowStyle.jsx
  src/Components/Follow/FollowUser.jsx
  src/Components/Follow/FollowingUser.jsx
  src/Components/Follow/Myfollowings.jsx
  src/Components/Header/Header.jsx
  src/Components/Header/HeaderBasic.jsx
  src/Components/Header/HeaderComponents.jsx
  src/Components/Header/HeaderHome.jsx
  src/Components/Header/HeaderKebab.jsx
  src/Components/Header/HeaderStyle.js
  src/Pages/Chat/ChatList.jsx
  src/Pages/Chat/ChatRoomAccount.jsx
  src/Pages/Chat/ChatRoomDarkHorse.jsx
  src/Pages/Chat/ChatRoomKim.jsx
  src/Pages/Chat/ChatRoomSumiDad.jsx
  src/Pages/Follow/FollowerList.jsx
  src/Pages/Follow/FollowingList.jsx
  src/Pages/Home/Home.jsx
  src/Pages/Post/EditPost.jsx
  src/Pages/Post/PostDetail.jsx
  src/Pages/Post/UploadPost.jsx
  src/Pages/Product/ProductAdd.jsx
  src/Pages/Product/ProductDetail.jsx
  src/Pages/Product/ProductEdit.jsx
  src/Pages/Product/ProductList.jsx
  src/Pages/Profile/EditProfile.jsx
  src/Pages/Profile/MyProfile.jsx
  src/Pages/Profile/ProfileStyle.js
  src/Pages/Profile/YourProfile.jsx
  src/Pages/Search/Search.jsx
Labels: ✅ 완료, ♻️ 리팩토링

#408 [♻️ Refactor] home feed 무한 스크롤 기능 추가
  src/API/Post/PostAPI.jsx
  src/Components/Header/HeaderHome.jsx
  src/Components/Skeleton/MyFollowingSkeleton.jsx
  src/Components/Skeleton/RecommendSkeleton.jsx
  src/Pages/Home/Home.jsx
Labels: ♻️ 리팩토링

#409 [♻️ Refactor / 🔧 Fix/ 🌈 Style] 페이지 UI수정 및 기능오류 수정
  src/Assets/icons/post-image-hover.svg
  src/Assets/icons/post-image.svg
  src/Components/Common/NavBarStyle.js
  src/Components/Profile/ProfileStyle.js
  src/Pages/Chat/ChatStyle.js
  src/Pages/Post/EditPost.jsx
  src/Pages/Post/UploadEditPostStyle.js
  src/Pages/Post/UploadPost.jsx
  src/Pages/Profile/EditProfileStyle.js
  src/Pages/Profile/ProfileStyle.js
  src/Pages/Profile/YourProfile.jsx
Labels: 🔧 수정, 🌈 스타일, ♻️ 리팩토링

#410 ♻️ Refactor]축제 리스트 스켈레톤 파일을 스켈레톤 폴더로 이동,스타일 수정
  src/Components/Product/ProductStyle.js
  src/Components/Skeleton/ProductListSkeleton.jsx
  src/Pages/Product/ProductList.jsx
Labels: ♻️ 리팩토링

#412 [♻️ Refactor] 축제 등록 이미지 용량 압축
  src/Utils/cropImage.js
Labels: ♻️ 리팩토링

#414 [♻️ Refactor 🔧 Fix] 축제 등록 시 이미지의 비율마다 등록되지 않는 오류
  src/Hooks/Common/useImage.jsx
Labels: ♻️ 리팩토링

#415 [♻️ Refactor] 이미지 압축 기능 추가
  package-lock.json
  package.json
  src/API/Post/PostAPI.jsx
  src/API/Profile/ProfileAPI.jsx
  src/Assets/images/loading.gif
  src/Components/Comment/Comment.jsx
  src/Components/Modal/DeleteModal.jsx
  src/Components/Post/PostItem.jsx
  src/Hooks/Common/useImage.jsx
  src/Pages/Home/Home.jsx
  src/Pages/Home/HomeSearch.jsx
  src/Pages/Home/HomeStyle.jsx
  src/Pages/Profile/MyProfile.jsx
  src/Utils/cropImage.js
Labels: ♻️ 리팩토링

#417 [♻️ Refactor] 메모이제이션, 접근성, SEO 개선
  package-lock.json
  package.json
  src/Breakpoints.jsx
  src/Components/Button/GoBackbtn.jsx
  src/Components/Button/HomeBtn.jsx
  src/Components/Comment/Comment.jsx
  src/Components/Common/ArticleUserProfile.jsx
  src/Components/Common/RecommendPlace.jsx
  src/Components/Follow/Myfollowings.jsx
  src/Components/Header/HeaderKebab.jsx
  src/Components/Post/Likefunc.js
  src/Components/Post/PostContents.jsx
  src/Components/Post/PostItem.jsx
  src/Components/Skeleton/PostItemSkeleton.jsx
  src/Pages/Auth/AuthStyle.jsx
  src/Pages/Home/Home.jsx
  src/Pages/Home/HomeSearch.jsx
  src/Pages/Post/UploadPost.jsx
Labels: ✅ 완료, ♻️ 리팩토링

#419 [♻️ Refactor]접근성, SEO 점수 향상
  src/Components/Button/GoBackbtn.jsx
  src/Components/Common/NavBar.jsx
  src/Components/Common/NavBarStyle.js
  src/Components/Follow/FollowUser.jsx
  src/Components/Follow/FollowingUser.jsx
  src/Components/Product/ProductOutput.jsx
  src/Components/Search/SearchStyle.js
  src/Pages/Chat/ChatList.jsx
  src/Pages/Follow/FollowingList.jsx
  src/Pages/Search/SearchStyle.js
Labels: ✅ 완료, ♻️ 리팩토링

#420 [🔧 Fix]console.log 삭제
  src/Components/Header/HeaderComponents.jsx
  src/Pages/Chat/ChatRoomDarkHorse.jsx
  src/Pages/Chat/ChatRoomKim.jsx
  src/Pages/Profile/EditProfile.jsx
Labels: ✅ 완료, 🔧 수정
