Repository FRONTENDSCHOOL7/final-18-moamoa, pull requests merged in 2024-01, with the labels that each got.

#338 [🔧fix] Components/Common/Header 폴더 생성,파일 이동
  moamoa/package-lock.json
  moamoa/package.json
  moamoa/src/Components/Common/Header/Header.jsx
  moamoa/src/Components/Common/Header/HeaderBasic.jsx
  moamoa/src/Components/Common/Header/HeaderComponents.jsx
  moamoa/src/Components/Common/Header/HeaderHome.jsx
  moamoa/src/Components/Common/Header/HeaderKebab.jsx
  moamoa/src/Pages/Chat/ChatList.jsx
  moamoa/src/Pages/Chat/ChatRoomAccount.jsx
  moamoa/src/Pages/Chat/ChatRoomDarkHorse.jsx
  moamoa/src/Pages/Chat/ChatRoomKim.jsx
  moamoa/src/Pages/Chat/ChatRoomSumiDad.jsx
  moamoa/src/Pages/Follow/FollowerList.jsx
  moamoa/src/Pages/Follow/FollowingList.jsx
  moamoa/src/Pages/Home/Home.jsx
  moamoa/src/Pages/Post/PostDetail.jsx
  moamoa/src/Pages/Product/ProductAdd.jsx
  moamoa/src/Pages/Product/ProductDetail.jsx
  moamoa/src/Pages/Product/ProductEdit.jsx
  moamoa/src/Pages/Product/ProductList.jsx
  moamoa/src/Pages/Profile/MyProfile.jsx
  moamoa/src/Pages/Profile/YourProfile.jsx
  moamoa/src/Pages/Search/Search.jsx
Labels: 📝 문서변경, ✅ 완료, 🔧 수정

#339 [🌈style]: 스타일컴포넌트 분리
  moamoa/src/Components/Common/Header/HeaderBasic.jsx
  moamoa/src/Components/Common/Header/HeaderComponents.jsx
  moamoa/src/Components/Common/Header/HeaderHome.jsx
  moamoa/src/Components/Common/Header/HeaderStyle.js
  moamoa/src/Components/Product/ProductListSkeleton.jsx
  moamoa/src/Components/Product/ProductOutput.jsx
  moamoa/src/Components/Product/ProductStyle.js
  moamoa/src/Components/Product/TopNavigation.jsx
  moamoa/src/Components/Search/NotFound.jsx
  moamoa/src/Components/Search/SearchResultBox.jsx
  moamoa/src/Components/Search/SearchSkeleton.jsx
  moamoa/src/Components/Search/SearchStyle.js
  moamoa/src/Components/Search/UserId.jsx
  moamoa/src/Components/Splash/LoginModal.jsx
  moamoa/src/Components/Splash/SplashLogo.jsx
  moamoa/src/Components/Splash/SplashStyle.js
  moamoa/src/Pages/Chat/ChatList.jsx
  moamoa/src/Pages/Chat/ChatRoomAccount.jsx
  moamoa/src/Pages/Chat/ChatRoomDarkHorse.jsx
  moamoa/src/Pages/Chat/ChatRoomKim.jsx
  moamoa/src/Pages/Chat/ChatRoomSumiDad.jsx
  moamoa/src/Pages/Chat/ChatStyle.js
  moamoa/src/Pages/Follow/FollowStyle.js
  moamoa/src/Pages/Follow/FollowerList.jsx
  moamoa/src/Pages/Follow/FollowingList.jsx
  moamoa/src/Pages/Product/ProductList.jsx
  moamoa/src/Pages/Product/ProductStyle.js
  moamoa/src/Pages/Search/Search.jsx
  moamoa/src/Pages/Search/SearchStyle.js
  moamoa/src/Pages/Splash/Landing.jsx
  moamoa/src/Pages/Splash/SplashStyle.js
Labels: ✅ 완료, ♻️ 리팩토링

#341 [♻️ Refactor] AuthFormStyle, ProductFormStyle 리팩토링
  moamoa/src/Components/Common/AuthFormStyle.jsx
  moamoa/src/Components/Common/ProductFormStyle.jsx
  moamoa/src/Components/Product/ProductForm.jsx
  moamoa/src/Components/Product/ProductFormStyle.jsx
  moamoa/src/Hooks/Auth/useSignUp.jsx
  moamoa/src/Pages/Auth/AuthStyle.jsx
  moamoa/src/Pages/Auth/Login.jsx
  moamoa/src/Pages/Auth/SignUp.jsx
Labels: ✅ 완료, ♻️ 리팩토링

#345 [♻️ Refactor] 재사용되는 이미지 크롭 함수들 훅으로 분리
  moamoa/src/Components/Product/ProductForm.jsx
  moamoa/src/Hooks/Auth/useSignUp.jsx
  moamoa/src/Hooks/Common/useImage.jsx
  moamoa/src/Hooks/Product/useProductData.jsx
  moamoa/src/Pages/Auth/SignUp.jsx
  moamoa/src/Pages/Post/EditPost.jsx
  moamoa/src/Pages/Post/UploadPost.jsx
  moamoa/src/Pages/Product/ProductAdd.jsx
  moamoa/src/Pages/Product/ProductEdit.jsx
  moamoa/src/Pages/Profile/EditProfile.jsx
Labels: ✅ 완료, ♻️ 리팩토링

#343 [♻️ Refactor]접근성 향상,색상 전역변수 지정,축제&체험 리스트 리코일 배열에 저장
  moamoa/src/Assets/icons/icon-img-button.svg
  moamoa/src/Components/Common/FollowUser.jsx
  moamoa/src/Components/Common/FollowingUser.jsx
  moamoa/src/Components/Common/SearchBtn.jsx
  moamoa/src/Components/Common/SearchHighLight.jsx
  moamoa/src/Components/Product/ProductOutput.jsx
  moamoa/src/Components/Product/ProductStyle.js
  moamoa/src/Components/Search/SearchStyle.js
  moamoa/src/Components/Splash/SplashLoginBtn.jsx
  moamoa/src/Components/Splash/SplashLogo.jsx
  moamoa/src/Components/Splash/SplashStyle.js
  moamoa/src/GlobalStyle.jsx
  moamoa/src/Pages/Chat/ChatStyle.js
  moamoa/src/Pages/Product/ProductList.jsx
  moamoa/src/Recoil/ProductAtom.jsx
Labels: 🌈 스타일, ♻️ 리팩토링

#347 [♻️ Refactor]유저 검색 페이지 렌더링 시 포커스
  moamoa/src/Components/Common/Header/HeaderComponents.jsx
Labels: ✅ 완료, ♻️ 리팩토링

#349 [♻️ Refactor]축제&체험 4개씩 렌더링,기한이 지난 축제&체험 필터링
  moamoa/src/API/Product/ProductAPI.jsx
  moamoa/src/Components/Product/ProductOutput.jsx
  moamoa/src/Components/Product/filterActive.js
  moamoa/src/Components/Product/formatEventDate.js
Labels: ✨ 기능추가, ✅ 완료, ♻️ 리팩토링

#353 [🛠️ Chore] package-lock.json에서 gh-pages 관련 코드 삭제
  moamoa/package-lock.json
Labels: ✅ 완료

#355 [♻️ Refactor] Home, 게시글 상세, 축제 및 체험 상세 CSS 분리
  src/Pages/Home/Home.jsx
  src/Pages/Home/HomeSearch.jsx
  src/Pages/Home/HomeStyle.jsx
  src/Pages/Post/PostDetail.jsx
  src/Pages/Post/PostDetailStyle.jsx
  src/Pages/Product/ProductDetail.jsx
  src/Pages/Product/ProductStyle.js
Labels: ✅ 완료, ♻️ 리팩토링

#356 [ 🔧 Fix ] 로그인 시 이전 사용자 데이터가 남는 오류
  src/Components/Common/Header/HeaderKebab.jsx
Labels: ✅ 완료, 🔧 수정

#358 [ 🔧 Fix ] 지도 출력 오류 해결
  public/index.html
  src/Components/Product/ProductContents.jsx
Labels: ✅ 완료, 🔧 수정

#360 [♻️ Refactor ] Footer 반응형 구현
  src/Assets/icons/icon-logout.svg
  src/Assets/icons/icon-tablet-Logo.svg
  src/Components/Common/Footer.jsx
Labels: 🌈 스타일, ♻️ 리팩토링

#363 refactor: home 페이지 반응형 구현
  src/Breakpoints.jsx
  src/Components/Common/Container.jsx
  src/Components/Post/PostContents.jsx
  src/Components/Post/PostItem.jsx
  src/Components/Post/PostList.jsx
  src/GlobalStyle.jsx
  src/Pages/Home/HomeStyle.jsx
Labels: 🚀 진행중, ♻️ 리팩토링

#364 [♻️ Refactor] develop brancg main branch로 merge
  public/index.html
  src/Assets/icons/icon-logout.svg
  src/Assets/icons/icon-tablet-Logo.svg
  src/Breakpoints.jsx
  src/Components/Common/Container.jsx
  src/Components/Common/Footer.jsx
  src/Components/Common/Header/HeaderKebab.jsx
  src/Components/Post/PostContents.jsx
  src/Components/Post/PostItem.jsx
  src/Components/Post/PostList.jsx
  src/Components/Product/ProductContents.jsx
  src/Components/Splash/LoginModal.jsx
  src/Components/Splash/SplashLogo.jsx
  src/Components/Splash/SplashStyle.js
  src/GlobalStyle.jsx
  src/Pages/Home/Home.jsx
  src/Pages/Home/HomeSearch.jsx
  src/Pages/Home/HomeStyle.jsx
  src/Pages/Post/PostDetail.jsx
  src/Pages/Post/PostDetailStyle.jsx
  src/Pages/Product/ProductDetail.jsx
  src/Pages/Product/ProductStyle.js
  src/Pages/Splash/Landing.jsx
  src/Pages/Splash/SplashStyle.js
  src/Recoil/modalActiveState .jsx
Labels: ♻️ 리팩토링

#365 [♻️ Refactor] 태블릿 navbar 왼쪽 정렬, 검색 버튼 추가, 로그아웃 기능 구현
  src/Assets/icons/icon-logout.svg
  src/Assets/icons/icon-message-fill.svg
  src/Assets/icons/icon-message.svg
  src/Assets/icons/icon-search-fill.svg
  src/Assets/icons/icon-searchWhite.svg
  src/Components/Common/Footer.jsx
  src/Components/Common/FooterStyle.js
  src/Components/Common/Header/HeaderKebab.jsx
  src/Recoil/logoutModalAtom.jsx
Labels: ✨ 기능추가, 🌈 스타일, ♻️ 리팩토링

#366 [♻️ Refactor/🌈 Style] home 화면, 게시글 상세페이지 태블릿 ui 구현
  src/Components/Comment/Comment.jsx
  src/Components/Comment/CommentAddBtn.jsx
  src/Components/Comment/CommentDelModal.jsx
  src/Components/Comment/CommentItem.jsx
  src/Components/Common/Container.jsx
  src/Components/Post/PostList.jsx
  src/Components/Skeleton/PostItemSkeleton.jsx
  src/GlobalStyle.jsx
  src/Pages/Home/HomeStyle.jsx
  src/Pages/Post/PostDetailStyle.jsx
Labels: 🚀 진행중, ♻️ 리팩토링

#367 [♻️ Refactor / 🌈 Style] 축제 상세 태블릿 ui 구현, 게시글 상세 nav bar 추가
  src/Components/Comment/Comment.jsx
  src/Components/Common/Header/HeaderKebab.jsx
  src/Components/Product/AskBtn.jsx
  src/Components/Product/FestaMap.jsx
  src/Components/Product/ProductContents.jsx
  src/Pages/Home/HomeStyle.jsx
  src/Pages/Post/PostDetail.jsx
  src/Pages/Post/PostDetailStyle.jsx
  src/Pages/Product/ProductDetail.jsx
  src/Pages/Product/ProductStyle.js
Labels: 🚀 진행중, ♻️ 리팩토링

#370 [♻️ Refactor]헤더,축제리스트,채팅 리스트,로그인,검색 반응형 작업
  src/Components/Common/Container.jsx
  src/Components/Common/Header/HeaderKebab.jsx
  src/Components/Common/Header/HeaderStyle.js
  src/Components/Common/ProductImgBox.jsx
  src/Components/Product/ProductStyle.js
  src/Components/Search/SearchStyle.js
  src/Pages/Auth/AuthStyle.jsx
  src/Pages/Chat/ChatList.jsx
  src/Pages/Chat/ChatStyle.js
  src/Pages/Home/HomeStyle.jsx
  src/Pages/Product/ProductList.jsx
  src/Pages/Search/Search.jsx
Labels: ♻️ 리팩토링

#369 [♻️ Refactor /✨ Feature ] 장소 추천 기능 추가
  src/API/Product/ProductAPI.jsx
  src/Components/Comment/Comment.jsx
  src/Components/Common/FooterStyle.js
  src/Components/Common/Header/HeaderStyle.js
  src/Components/Common/RecommendPlace.jsx
  src/Components/Post/PostList.jsx
  src/GlobalStyle.jsx
  src/Pages/Home/Home.jsx
  src/Pages/Home/HomeStyle.jsx
  src/Pages/Product/ProductDetail.jsx
Labels: ✨ 기능추가, ♻️ 리팩토링

#371 [♻️ Refactor /✨ Feature ] MyFollowing 컴포넌트 구현
  src/API/Follow/FollowAPI.jsx
  src/Components/Comment/Comment.jsx
  src/Components/Common/Myfollowings.jsx
  src/Components/Common/RecommendPlace.jsx
  src/Pages/Follow/FollowerList.jsx
  src/Pages/Follow/FollowingList.jsx
  src/Pages/Home/Home.jsx
  src/Pages/Post/PostDetailStyle.jsx
Labels: ✨ 기능추가, ♻️ 리팩토링
